### ISSUE TITLE
[Feature Request] Add support for hiding Verizon 4G LTE icon.

### ISSUE THREAD

**Issue by tnyeanderson** [zacharee/SystemUITunerRedesign#20]
![status bar](https://user-images.githubusercontent.com/9835153/39962888-54ae3bfc-562a-11e8-829b-c7e891205297.png)

The icon between the wifi and battery percentage cannot be hidden with SystemUI Tuner. This may not be possible. It is an LG/Verizon icon, and when network traffic is occurring over 4G LTE, arrows appear (similar to those below the wifi icon) to indicate traffic. I would LOVE to be able to hide this icon, as it's incredibly ugly and takes up an entire extra spot in my status bar!

Let me know if this is possible!

Edit: I'm using an LG V30 VS996

**Comment by zacharee** [comment]
This isn't possible.
