### ISSUE TITLE
Why the permanent 'Safe Mode' notification?

### ISSUE THREAD

**Issue by Eisys** [zacharee/SystemUITunerRedesign#28]
S8+
I installed this just to make my navbar black.

Now after a restart this notification exists and you recommended in a review reply to just turn it off.. But why is it there in the first place and what does safe mode mean in this context?

**Comment by zacharee** [comment]
Android requires that any Services an app runs show a persistent notification. There's no way around this restriction on my end.

Safe Mode clears and resets certain values on reboot. On reboot, some devices force them back to default and others crash if they aren't default.

**Comment by Eisys** [comment]
Gotcha, thanks.
