### ISSUE TITLE
Hide VoLTE icon on HTC U11

### ISSUE THREAD

**Issue by kennethso168** [zacharee/SystemUITunerRedesign#3]
Details as mentioned in https://forum.xda-developers.com/showpost.php?p=73250701&postcount=462. The key for the VoLTE icon is "ims_indicator".

I don't know if this works on other HTC devices, other variants (I have a Hong Kong dual sim version) or cause other problems in other devices.

Clues can be found by running `adb shell dumpsys activity service com.android.systemui/.SystemUIService`. [Dumpsys file](https://github.com/zacharee/SystemUITunerRedesign/files/1190825/system_ui_service_dump_u11.txt)

**Comment by zacharee** [comment]
I'll add it.
