### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by dimqua** [zacharee/SystemUITunerRedesign#4]
Please consider to add the app to F-Droid. 

In order to do this, you need [to make crashlytics library optional](https://developer.android.com/studio/build/build-variants.html#product-flavors) or get rid of it.

**Comment by zacharee** [comment]
I had enough trouble building for Play and Labs before Labs died on me. Crashlytics can already be disabled in the options, but either way, I'm not sure I want to go back to double-building again.

**Comment by IzzySoft** [comment]
@zacharee if you could at least publish the `.apk` here at Github, I might be able to provide it via [my F-Droid compatible repo](https://apt.izzysoft.de/fdroid) – if it's not too big, that is (running on my personal space only, no sponsor for hardware).

**Comment by IzzySoft** [comment]
Hm, sad. So folks who don't/can't use Play Store are left out.
