### ISSUE TITLE
Icon Keys List

### ISSUE THREAD

**Issue by resistdesign** [zacharee/SystemUITunerRedesign#50]
Trying to hide the No SIM card icon with a custom item but I don't know the key. Is it possible to list the keys of the current icons?

**Comment by puwei7788** [comment]
managed_profile
ime
sync_failing
sync_active
cast
location
bluetooth
powersavingmode
earphone
nfc
tty
speakerphone
zen
mute
volume
wifi
cdma_eri
data_connection
phone_evdo_signal
phone_signal
battery
alarm_clock
secure
clock
volte_call
eyes_protect
