### ISSUE TITLE
display turns off and no return to on when press the "nigth display"

### ISSUE THREAD

**Issue by avida-a** [zacharee/SystemUITunerRedesign#60]
i just has ativated the "immersive mode" and when i press the "nigth display" the screen slowly blacked out and no turn on again in my Samsung a50
 
the phone still works, I can connect my headphones via bluetooth and listen to music

**Comment by zacharee** [comment]
Run the following ADB command: `adb shell settings put secure ui_night_mode 0`.

That option is broken on One UI 2. There's nothing I can do about it.

**Comment by avida-a** [comment]
I managed to reverse the problem by hard resetting the phone. thanks for answering
