### ISSUE TITLE
Why is the high brightness toggle greyed out? 

### ISSUE THREAD

**Issue by NovaViper** [zacharee/SystemUITunerRedesign#7]
On my Sprint Samsung S6 Edge running Android 7.0.1, I notice the high brightness toggle is greyed out. I'm curious to why that is and want to know if there is some sort of work around it. I really hate the high brightness warning

**Comment by KazWolfe** [comment]
It's there because there's no reliable way to disable that warning yet as far as anyone can tell.

I'd assume that once a way to bypass that is discovered, it will be re-enabled.

**Comment by zacharee** [comment]
HBW toggle removed.
